### ISSUE TITLE
Step 13 - compile

### ISSUE THREAD

**Issue by streamnsight** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#1]
Compiling with -j3 failed for me.

`make` alone tooks 7h or so but it worked fine.

**Comment by Tes3awy** [comment]
@streamnsight If you are using Raspberry Pi B or lower, you can't use make -j3, you can only use make -j2 and I don't prefer this

**Comment by streamnsight** [comment]
It's a RPi 2 B, `nproc` reports 4, so -j3 should work, but I read other threads that recommended not using multi processors... just wanted to point it out over here in case others see failure at that step.

Anyhow, typically the `j` param should be #cores + 1; that's how I was recommended, and that's what I use to compile kernels on my dual Xeon without issues.

**Comment by Tes3awy** [comment]
@streamnsight Then I should update the cheat sheet. Thanks for the tip ;)
