### ISSUE TITLE
Step 12 error on Raspberry Pi 3

### ISSUE THREAD

**Issue by DGaffney** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#2]
Hello! This checklist you've written is super super helpful, thank you for the work. A question for you, if you think you can figure out what's going on - I followed your directions line by line, but when running `sudo make -j3`, I get the following error:
```
[ 36%] Linking CXX shared library ../../lib/libopencv_videoio.so
[ 38%] Built target opencv_shape
/usr/bin/ld: /usr/local/lib/libx264.a(common.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libx264.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:227: recipe for target 'lib/libopencv_videoio.so.3.1.0' failed
make[2]: *** [lib/libopencv_videoio.so.3.1.0] Error 1
CMakeFiles/Makefile2:5832: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
Now, there's people that say you can get past this issue by just passing WITH_FFMPEG to false during the cmake step just before this - but I'm working with .avi files, so I can't just skip this because I'll need it to actually work. Any thoughts on how to fix this one?

**Comment by Tes3awy** [comment]
@DGaffney  Try running `sudo make` without specifying the number of cores.  This should work, but be aware that it wil take longer time to complete the process. You can leave it over night, grab a cup of coffee, or watch one of your favorite movies :D

**Comment by DGaffney** [comment]
Alright - I'm trying to install ffmpeg directly one more time and then failing that, I'll not specify cores and go on vacation for a week and maybe it'll be compiled by then :) - if you're ok with it I'd love to keep this open until I confirm that fixes it?

**Comment by Tes3awy** [comment]
@DGaffney Sure, and thanks a lot for you kind words :)

**Comment by DGaffney** [comment]
Thanks for this checklist!

**Comment by Tes3awy** [comment]
@DGaffney You are more than welcome

**Comment by Tes3awy** [comment]
@DGaffney I googled about your problem, and yes it "sometimes" causes issues for some people. So now I decided to update my checklist to OpenCV 3.2.0. The good part is, you can use OpenCV on your RPI without have to specify **`-D WITH_FFMPEG=ON`**. The **CMakeList.txt** provided by OpenCV turns it on by default. therefore, you can manipulate avi videos on RPi. The following line is included in the **CMakeList.txt**:`

OCV_OPTION(WITH_FFMPEG "Include FFMPEG support" ON IF (NOT ANDROID AND NOT IOS AND NOT WINRT) )`

I tried it myself and it works fine for me right now.

I know this solution might be annoying for some people, but delete all opencv directories you already downloaded, and start from step 11. Also now you can freely use `sudo make -j3` if you want.

**Comment by DGaffney** [comment]
@Tes3awy alright, this sounds good - I'll give it a try! For what it's worth, the make still failed with same situation:

```
[ 10%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_libv4l.cpp.o
[ 11%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
In file included from /home/pi/opencv-3.1.0/modules/videoio/src/cap_ffmpeg.cpp:45:0:
/home/pi/opencv-3.1.0/modules/videoio/src/cap_ffmpeg_impl.hpp: In member function ‘bool OutputMediaStream_FFMPEG::open(const char*, int, int, double)’:
/home/pi/opencv-3.1.0/modules/videoio/src/cap_ffmpeg_impl.hpp:2207:41: warning: ignoring return value of ‘int avformat_write_header(AVFormatContext*, AVDictionary**)’, declared with attribute warn_unused_result [-Wunused-result]
         avformat_write_header(oc_, NULL);
                                         ^
[ 11%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/local/lib/libx264.a(common.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libx264.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:227: recipe for target 'lib/libopencv_videoio.so.3.1.0' failed
make[2]: *** [lib/libopencv_videoio.so.3.1.0] Error 1
CMakeFiles/Makefile2:5832: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by DGaffney** [comment]
The error still happens, but it didn't crash this time? I'm still at 33% so I'll report in tomorrow once it's finished running, but here's that output just in case you wanted to see it:

```
[ 32%] Building CXX object modules/shape/CMakeFiles/opencv_shape.dir/src/tps_trans.cpp.o
[ 32%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
[ 32%] Linking CXX shared library ../../lib/libopencv_shape.so
[ 32%] Linking CXX shared library ../../lib/libopencv_videoio.so
[ 32%] Built target opencv_shape
[ 32%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/blob.cpp.o
/usr/bin/ld: /usr/local/lib/libx264.a(common.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libx264.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:228: recipe for target 'lib/libopencv_videoio.so.3.2.0' failed
make[2]: *** [lib/libopencv_videoio.so.3.2.0] Error 1
CMakeFiles/Makefile2:6433: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by DGaffney** [comment]
Spoke too soon! It did fail shortly thereafter:

```
[ 34%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o
[ 34%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o
[ 34%] Linking CXX shared library ../../lib/libopencv_dnn.so
[ 34%] Built target opencv_dnn
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by DGaffney** [comment]
Latest update - I decided to reset the RPi to a clean install of the OS (Jessie with Pixel, 2017-03-02 release), and only do a few things after install before leading into your checklist (install tmux, allow ssh, and nothing else). Before running cmake in Step 11, I followed directions from https://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/ to install ffmpeg. Nearly all the way through, I hit an error while using sudo make -j3 in Step 12:

```
BUILD SUCCESSFUL
Total time: 1 minute 3 seconds
Scanning dependencies of target opencv_java
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/Mat.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/converters.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/jni_part.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp/utils.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/__/core/misc/java/src/cpp/core_manual.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/__/features2d/misc/java/src/cpp/features2d_converters.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/core.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/imgproc.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/ml.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/photo.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/video.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/imgcodecs.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/videoio.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/objdetect.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/bioinspired.cpp.o
[ 82%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/features2d.cpp.o

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
modules/python2/CMakeFiles/opencv_python2.dir/build.make:320: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o' failed
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 4
CMakeFiles/Makefile2:20806: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/calib3d.cpp.o
[ 83%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/xfeatures2d.cpp.o
[ 83%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/aruco.cpp.o
[ 83%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/phase_unwrapping.cpp.o
[ 83%] Building CXX object modules/java/CMakeFiles/opencv_java.dir/gen/structured_light.cpp.o
[ 83%] Linking CXX shared library ../../lib/libopencv_java320.so
[ 83%] Built target opencv_java
[ 83%] Linking CXX shared module ../../lib/python3/cv2.cpython-34m.so
[ 83%] Built target opencv_python3
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm running sudo make without multiple cores now to see if that can bypass the issue, the "Killed" printout makes me feel like the issue is due to resource constraints rather than anything to do with the current build. I'll reply after this finishes up either tonight if I'm feeling like waiting around (2:30am local here) or when I wake up (afternoon in your TZ if you're in Cairo).

**Comment by DGaffney** [comment]
Another update (because of course I stayed up to see if it would compile) - we are now compiled! The only note that I would add is that your checklist doesn't cover installs of ffmpeg. Before cmake in step 11, people need to install ffmpeg from source (or maybe from apt-get, though I didn't try that so I can't directly vouch for that approach). Either way, to make this checklist compliant with the latest RPi build, before cmake, you need to do the following:

```
cd /usr/src
git clone https://github.com/FFmpeg/FFmpeg.git
cd ffmpeg
sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
make
sudo make install
```

Again, that's sourced from https://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/

I'm now able to confirm that cv2 is reporting version 3.2.0 in python, so the issues I had are now dealt with, but I think that you should add in the checklist the step provided above, since you aren't explicitly stating that users should install ffmpeg, and as a result, this use case would still likely fail - up to you, however, so I'll leave it with this comment, up to you to close! Thanks for everything and all the feedback - greatly appreciated.

**Comment by ChickenSoup2019** [comment]
I started with raspberry pi 2 model B. it's worked, but when I install it for raspberry pi 3 model B, it shows the same error message and then I follow this site, it's worked for me
http://pklab.net/?id=392&lang=EN

**Comment by esmacolak** [comment]
for python3
`sudo apt-get install python3-opencv` 
for python2
`sudo apt-get install python2-opencv`

Easy install
[http://jollejolles.com/easy-install-opencv-for-python-on-mac-ubuntu-and-raspberry-pi/](url)
