### ISSUE TITLE
sudo apt-get install libgtk2.0-dev [SOLVED]

### ISSUE THREAD

**Issue by iklobato** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#3]
The following error

> The following packages have unmet dependencies:
>   libglib2.0-dev: Depends: libglib2.0-0 (= 2.24.0-0ubuntu4) but 2.24.1-0ubuntu1 is to be installed
> E: Broken packages

Can be solved by
`sudo aptitude install libglib2.0-dev`

Then, it will be asked for downgrade some version

> The following actions will resolve these dependencies:
>      Install the following packages:                                 
>      libelfg0 [0.8.13-5 (now, oldstable)]                          
>      Downgrade the following packages:                               
>      libglib2.0-0 [2.48.0-1 bpo8+1 (now) -> 2.42.1-1 (oldstable)]  
>      libglib2.0-bin [2.48.0-1 bpo8+1 (now) -> 2.42.1-1 (oldstable)]
>       Accept this solution? [Y/n/q/?] 

And finally
`sudo apt-get install libglib2.0-dev`

**Comment by iklobato** [comment]
I just realize the problem was in the repository, here its how to fix it,
`sudo nano /etc/apt/sources.list`

As the official website says [here](https://www.raspbian.org/RaspbianRepository), change it to:

> deb http://archive.raspbian.org/raspbian wheezy main contrib non-free
> deb-src http://archive.raspbian.org/raspbian wheezy main contrib non-free

And then:
`sudo reboot`

**Comment by smug-dev** [comment]
ily
