### ISSUE TITLE
Created menu assisted bash script for opencv3 install

### ISSUE THREAD

**Issue by pageauc** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#4]
Menu Assisted Opencv 3.2.0 Install   https://github.com/pageauc/opencv3-setup

I have created a bash script that implements most of your steps using a whiptail menu.  This allows a bit of an assist for users that might need help cutting and pasting commands into a terminal session.  I did have lockup problem running make on a RPI3 with -j3 so changed to -j2 and seems to work better although slower.  I have not tested this extensively on other RPI models.  Raise an github issue if there are problems

I have credited your repo on the Readme.md

Thanks Claude Pageau

**Comment by pageauc** [comment]
Release 0.4x https://github.com/pageauc/opencv3-setup
Made quite a few changes and doing a full test install on a recent build.  Add prompt for quad core but this could be automated.  Tried to implement Step 14 but system security will not allow changing the files.  They can be changed using nano from the command line but not indirectly from the script so I have added a note to the project Readme.md

**Comment by pageauc** [comment]
Not sure what assign means.  Do I just have to maintain my GithHub repo copy or do I have to do something else. Claude ....

**Comment by Tes3awy** [comment]
You are assigned as one of the contributors to this Issue, Sir.
