### ISSUE TITLE
Installing OpenCV 3.3.0 with opencv-contrib on Raspberry Pi 3, but got error during make

### ISSUE THREAD

**Issue by shakil10vr** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#5]
Hi,
I installing opencv 3.3.0 on my raspberry pi 3, using the cmake with the following configure:
cmake -D CMAKE_BUILD_TYPE=RELEASE 
-D INSTALL_C_EXAMPLES=OFF 
-D INSTALL_PYTHON_EXAMPLES=ON 
-D CMAKE_INSTALL_PREFIX=/usr/local 
-D WITH_V4L=ON 
-D INSTALL_CREATE_DISTRIB=ON 
-D ENABLE_NEON=ON 
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules 
-D BUILD_EXAMPLES=ON ..

But ended up, with the following error

CMakeFiles/opencv_perf_imgproc.dir/__/imgproc/perf/opencl/perf_pyramid.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
modules/world/CMakeFiles/opencv_perf_imgproc.dir/build.make:1033: recipe for target 'bin/opencv_perf_imgproc' failed
make[2]: *** [bin/opencv_perf_imgproc] Error 1
CMakeFiles/Makefile2:5038: recipe for target 'modules/world/CMakeFiles/opencv_perf_imgproc.dir/all' failed
make[1]: *** [modules/world/CMakeFiles/opencv_perf_imgproc.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by toponsky** [comment]
I got same error here.

**Comment by Tes3awy** [comment]
Try to clean the make and then retry. If the problem presists, just give me a nudge.

**Comment by shakil10vr** [comment]
I was able to fix the problem
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D WITH_V4L=ON \
-D INSTALL_CREATE_DISTRIB=ON \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.3.0/modules \
-D BUILD_opencv_python3=ON \
-D BUILD_EXAMPLES=ON ..

This config worked for me.

**Comment by maaxdq** [comment]
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:115: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_gstreamer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4976: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....


help me out
