### ISSUE TITLE
Menu Driven opencv3 Install on Raspberry Pi

### ISSUE THREAD

**Issue by pageauc** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#6]
FYI I have added credit for your work on my opencv3 menu assisted install project
https://github.com/pageauc/opencv3-setup
Thanks Claude ...

**Comment by Tes3awy** [comment]
Thanks a lot for the credit. I really appreciate it 😊

Regards;
Osama Abbas
