### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by vibhoregit** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#7]
I compiled opencv 3.2 and followed every step till the last one but as soon as I import cv2 the command prompt says illegal instruction and quits out of python shell. library compiled for raspberry pi zero W, running raspbian stretch lite.

**Comment by Tes3awy** [comment]
@vibhoregit I don't know if this works on RPi Zero. I haven't tried it as I have no access to one.
