### ISSUE TITLE
Add SWAP size on Raspberry Pi B+

### ISSUE THREAD

**Issue by MattiaFailla** [Tes3awy/OpenCV-3.2.0-Compiling-on-Raspberry-Pi#8]
Hello! 
In order to maximize success you should consider to insert a small guide on how to add more swap space to the Raspberry. I've been stuck for a lot of time because of the lack of RAM. 

If you want I can insert a small guide into the existing file.

Bye,
Mattia.

**Comment by Tes3awy** [comment]
@MattiaFailla Can you please add a pull request following the [guidelines](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)? Thank you
